var utag_data = {
	"customer_childrenQuantity":"",
	"customer_childrenQuantity":"",
	"customer_companyName":"",
	"customer_companyRole":"",
	"customer_cpf":"",
	"customer_dateBirth":"",
	"customer_dateBirth":"",
	"customer_freq_tripYear":"",
	"customer_gender":"",
	"customer_gender":"",
	"customer_language":"",
	"customer_language":"",
	"customer_marital status":"",
	"customer_marital status":"",
	"customer_phone":"",
	"customer_prefDestination":"",
	"customer_prefOrigin":"",
	"pageName":"",
	"section":"",
	"siteLanguage":"",
	"user_email":"",
	"user_name":"",
	"user_pointsBalance":"",
	"user_tudoAzulNumber":"",
	"user_userClassification":"",
	"visitorLoginStatus":""
}